FROM node:21-alpine3.18 as builder

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN npm install -g npm@latest
RUN npm ci && npm run build

FROM node:21-alpine3.18

WORKDIR /app
RUN apk add --no-cache curl
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
RUN npm install -g pm2 npm@latest
RUN npm ci --production
COPY --from=builder /app/build ./build

EXPOSE 4001

CMD [ "npm", "run", "start" ]


# FROM node:18-alpine

# WORKDIR /app

# ARG NPM_TOKEN

# COPY package.json ./

# COPY tsconfig.json ./

# COPY src ./src

# COPY tools ./tools

# RUN echo "@abdulmanan-ali:registry=https://npm.pkg.github.com" > .npmrc && \
#     echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc && \
#     cat .npmrc && \
#     npm install && \
#     rm -f .npmrc && \
#     npm install -g nodemon

# EXPOSE 4001

# CMD [ "npm", "run", "dev" ]
